defmodule Loomkin.Orchestration.Committers.Git do
  @moduledoc """
  Real git committer.

  Payload keys:

    * `:worktree_path` (required) — the worktree directory
    * `:work_unit_id` (optional) — included in commit message
    * `:files_touched` (optional) — list of paths to stage; if absent, stages all changes
    * `:verdict_summary` (optional) — short verdict line to include in commit body

  Returns `{:ok, sha}` where `sha` is the resulting commit SHA. Returns
  `{:error, {:nothing_to_commit, _}}` if there are no changes (so the work
  unit can be flagged as a no-op).
  """
  @behaviour Loomkin.Orchestration.Committers.Committer

  @impl true
  def name, do: :git

  @impl true
  def commit(payload, _opts \\ []) do
    case payload[:worktree_path] || payload["worktree_path"] do
      nil ->
        {:error, :missing_worktree_path}

      path when is_binary(path) ->
        do_commit(path, payload)
    end
  end

  defp do_commit(path, payload) do
    with :ok <- stage(path, payload),
         :ok <- ensure_changes(path) do
      do_git_commit(path, payload)
    end
  end

  defp stage(path, payload) do
    args =
      case payload[:files_touched] || payload["files_touched"] do
        nil -> ["add", "-A"]
        [] -> ["add", "-A"]
        files when is_list(files) -> ["add", "--"] ++ files
      end

    case System.cmd("git", args, cd: path, stderr_to_stdout: true) do
      {_out, 0} -> :ok
      {out, code} -> {:error, {:stage_failed, code, out}}
    end
  end

  defp ensure_changes(path) do
    case System.cmd("git", ["diff", "--cached", "--quiet"], cd: path, stderr_to_stdout: true) do
      {_out, 0} ->
        {:error, {:nothing_to_commit, "no staged changes"}}

      {_out, 1} ->
        :ok

      {out, code} ->
        {:error, {:diff_check_failed, code, out}}
    end
  end

  defp do_git_commit(path, payload) do
    wu_id = payload[:work_unit_id] || payload["work_unit_id"] || "unknown"
    verdict = payload[:verdict_summary] || payload["verdict_summary"] || ""

    subject = "chore(orchestration): work unit #{wu_id}"

    body =
      [
        "Generated by Loomkin orchestration.",
        if(verdict != "", do: "Verdict: #{verdict}", else: nil)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join("\n\n")

    message = subject <> if(body == "", do: "", else: "\n\n" <> body)

    case System.cmd("git", ["commit", "-m", message], cd: path, stderr_to_stdout: true) do
      {_out, 0} ->
        case System.cmd("git", ["rev-parse", "HEAD"], cd: path, stderr_to_stdout: true) do
          {sha, 0} -> {:ok, String.trim(sha)}
          {out, code} -> {:error, {:rev_parse_failed, code, out}}
        end

      {out, code} ->
        {:error, {:commit_failed, code, out}}
    end
  end
end
